trigger:
- main

pool: Arvind_agent


steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
